- name: get device facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: read secrets
      ansible.builtin.include_vars:
        file: secret.yaml
    - name: send slack notification
      delegate_to: 127.0.0.1
      community.general.slack:
        token: "{{ secret.api_token }}"
        msg: "getting facts from: `{{ inventory_hostname }}`"
    - name: get facts
      arista.eos.facts:
        gather_subset:
          - all
    - name: print facts
      debug:
        var: ansible_facts
