- name: get device facts
  hosts: all
  gather_facts: no
  tasks:
    - name: read secrets
      ansible.builtin.include_vars:
        file: secret.yaml
    - name: get version
      arista.eos.eos_command:
        commands: "show version"
      register: version
    - name: print facts
      debug:
        var: version.stdout_lines
    - name: send slack notification
      community.general.slack:
        token: "{{ secret.api_token }}"
        msg: "EOS version: `{{ inventory_hostname }}`: `{{ version.stdout_lines }}`"
