- name: azure provisioning template
  hosts: all
  gather_facts: no
  tasks:
    - name: interface configuration
      arista.eos.eos_config:
        src: templates/{{ target_os }}/{{ template_name }}.j2
        save_when: modified
