- name: get device facts
  hosts: all
  gather_facts: false
  tasks:
    - name: read secrets
      ansible.builtin.include_vars:
        file: secret.yaml
    - name: send slack notification
      community.general.slack:
        token: "{{ secret.api_token }}"
        msg: "getting facts from: `{{ inventory_hostname }}`"
    - name: get facts
      ipinfusion.ocnos.ocnos_facts:
        gather_subset:
          - all
    - name: print facts
      debug:
        var: ansible_facts
