- name: get device facts
  hosts: all
  gather_facts: no
  tasks:
    - name: read secrets
      delegate_to: 127.0.0.1
      ansible.builtin.include_vars:
        file: secret.yaml
    - name: get version
      ipinfusion.ocnos.ocnos_command:
        commands: "show version"
      register: version
    - name: print facts
      debug:
        var: version.stdout_lines
    - name: send slack notification
      delegate_to: 127.0.0.1
      community.general.slack:
        token: "{{ secret.api_token }}"
        msg: "ocnos version: `{{ inventory_hostname }}`: `{{ version.stdout_lines }}`"
