- name: azure provisioning template
  hosts: all
  gather_facts: no
  tasks:
    - name: read secrets
      ansible.builtin.include_vars:
        file: secret.yaml
    - name: interface configuration
      ipinfusion.ocnos.ocnos_config:
        src: templates/ocnos/{{ template_name }}.j2
        save_when: modified
      register: config_result
    - name: debug
      debug:
        var: config_result
    - name: send slack notification
      community.general.slack:
        token: "{{ secret.api_token }}"
        msg: "config apply result on device `{{ inventory_hostname }}`: \n```{{ config_result }}```"

