- name: just a playbook
  hosts: all
  ansible_connection: ansible.netcommon.httpapi
  ansible_network_os: arista.eos.eos
  ansible_become: yes
  ansible_become_method: enable
  gather_facts: no
  tasks:
    - name: set hostname
      arista.eos.eos_config:
        lines:
          - hostname {{ inventory_hostname }}
        save_when: modified
