- name: just a playbook
  hosts: all
  connection: httpapi
  gather_facts: no
  tasks:
    - name: set hostname
      arista.eos.eos_config:
        lines:
          - hostname {{ inventory_hostname }}
        save_when: modified
